#!/usr/bin/env ansible-playbook
---
- hosts: local
  vars: 
    user: s.kupstaitis-dunkler
    workspace_path: ~/workspace/private/
    chefdk_deb_filename: /tmp/chefdk.deb
  sudo: yes
  tasks:
    - name: install ubuntu packages
      apt: pkg={{ item }} state=installed
      with_items:
        - git
        - git-flow
        - gitk
        - ansible
        - automake
        - build-essential
        - chromium-browser
        - docker.io
        - ipython
        - mosh
        - nodejs-legacy
        - npm
        - openjdk-7-jdk
        - python-pip
        - ruby-dev
        - python-dev
        - vagrant
        - terminator
        - vim
        - cowsay
        - htop
        - bc
        - ranger
        - ngrep
        - dtrx
        - dstat
        - libfreetype6-dev
        - libblas3
        - gfortran
        - liblapack3
        - libblas-dev
        - liblapack-dev
        - libatlas-base-dev
        - freeipa-client
        - sysstat

    - name: install python modules with pip
      pip: name={{ item }}
      with_items:
        - awscli
        - jupyter
        - matplotlib
        - flake8
        - nose
        - vim_bridge
        - mock
        - numpy
        - scipy
        - pandas
        - scikit-learn
        - scikit-image
   
    - name: install Vundle
      git: repo='https://github.com/VundleVim/Vundle.vim.git' dest='~/.vim/bundle/Vundle.vim'

    - name: install Vundle plugins
      command: "vim -E -s -c 'source ~/.vimrc' -c PluginInstall -c qa"
      register: vundle_install
      failed_when: vundle_install.rc > 1
      changed_when: vundle_install.rc == 1

      
    - name: install node.js packages with npm
      npm: name={{ item }} global=yes
      with_items:
        - azure-cli

    - name: deploy bashrc file
      copy: src=./files/.bashrc dest=/home/{{ user }}/.bashrc owner={{ user }} group={{ user }}
      
    - name: deploy vimrc file
      copy: src=./files/.vimrc dest=/home/{{ user }}/.vimrc owner={{ user }} group={{ user }}
      
    - name: deploy ssh config file
      copy: src=./files/ssh_config dest=/home/{{ user }}/.ssh/config owner={{ user }} group={{ user }}

    - name: download powerline fonts
      git: repo='https://github.com/powerline/fonts.git' dest='{{ workspace_path }}/fonts'
      notify:
        - install powerline fonts

    - name: check if chefdk is installed
      command: dpkg-query -W chefdk
      register: is_chefdk_installed
      failed_when: is_chefdk_installed.rc > 1
      changed_when: is_chefdk_installed.rc == 1
      notify:
        - download chefdk

  handlers:
    - name: install powerline fonts
      command: "{{ workspace_path }}/fonts/install.sh"

    - name: download chefdk
      command: "wget 'https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chefdk_0.11.2-1_amd64.deb' -o {{ chefdk_deb_filename }}"
      notify:
        - install chefdk
    
    - name: install chefdk
      apt: deb="{{ chefdk_deb_filename }}"

